from enum import Enum

class Relation(Enum):
    ACCEPTED = 1
    REFUSED = 2
    USER_REFUSED = 3
    USER_ACCEPTED = 4
    UNCONTACTED = 5

class RequestType(Enum):
    GET_AGENT_RELATIONS = 1
    GET_REGISTERED_AGENTS = 2
    GET_PERSONAL_RELATIONS = 3
    GET_PUBLIC_INFORMATION = 4
    GET_PRIVATE_INFORMATION = 5
    GET_POLICIES = 6
    GET_USER_INFORMATION = 7
    GET_AGENT_RELATIONS_FULL = 8
    GET_PENDING_HUMAN_APPROVAL = 9
    GET_ESTABLISHED_RELATIONS = 10
    GET_UNFEEDBACK_RELATIONS = 11
    GET_MODELS = 12

class ActionType(Enum):
    PAUSE_AGENT = 1
    RESUME_AGENT = 2
    DELETE_AGENT = 3
    RESET_AGENT = 4

class ModelType(Enum):
    OLLAMA = 1
    OPENAI = 2
    GEMINI = 3
    MISTRAL = 4

class Status(Enum):
    COMPLETED = 1
    FAILED = 2
    REPEATED = 3